language: rust
rust:
  - stable
  - nightly
before_script:
  - rustup component add rustfmt-preview
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test --verbose
notifications:
  slack:
    rooms:
      - guni-safehouse:jCLEw1jQKtWWAHbvdd1E09Id#ace
