language: rust
rust:
  - nightly
before_script:
  - rustup component add rustfmt-preview
script:
  - cargo fmt --all -- --check
  - cargo build --verbose --all
  - cargo test
notifications:
  slack:
    rooms:
      - guni-safehouse:jCLEw1jQKtWWAHbvdd1E09Id#ace
