[package]
name = "cromwell"
version = "0.1.0"
authors = ["Takashi IIGUNI <ad2314ce71926@gmail.com>"]
description = "Rust Rootless Container Runtime"
license = "MIT"
repository = "https://github.com/guni192/cromwell"
edition = "2018"

[dependencies]
nix = "0.11.0"
getopts = "0.2"
dirs = "1.0"
clap = "2.32.0"
libc = "*"
