[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.install]
command = "cargo"
args = ["install", "--git", "https://github.com/guni1192/cromwell"]
dependencies = ["clean"]

[tasks.workflow]
dependencies = [
    "format",
    "build",
    "test",
]
